name: Tests
on:
  push:
    branches: [main, "*.x"]
  pull_request:
permissions:
  contents: read
jobs:
  php:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, fileinfo, json, mbstring
          coverage: none
      - run: composer update --prefer-dist --no-interaction
      - run: composer test
      - run: composer types
      - run: vendor/bin/pint --test
